name: Deploy to Caprover

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      password:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy image
        uses: floms/action-caprover@v1
        with:
          host: ${{inputs.server}}
          password: ${{inputs.password}}
          app: "${{ github.event.repository.name }}-${{github.ref_name}}"
          image: "ghcr.io/${{github.event.repository.owner.name}}/${{ github.event.repository.name }}:${{github.ref_name}}"
