name: Migrate DB

on:
  workflow_call:
    secrets:
      DATABASE_URL:
        required: true
        description: URL of your database
      database_id:
        required: true
        description: The DO database's id
      DO_TOKEN:
        required: true
        description: The token used to access DO

jobs:
  migrate:
    name: Migrate Database
    runs-on: ubuntu-latest
    steps:
      - name: Add IP address to trusted source (managed database)
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "add"
          database_id: ${{secrets.database_id}}
          digitalocean_token: "${{ secrets.DO_TOKEN }}"
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
      
      - name: Add DB URL
        run: echo "DATABASE_URL=${{secrets.DATABASE_URL}}" > .env
        shell: bash
      
      - name: NPM Install
        run: npm install --force
        shell: bash
      
      - name: NPM DB Update
        run: npm run db:update
        shell: bash

      - name: Remove IP address to trusted source (managed database)
        if: always()
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "remove"
          database_id: ${{secrets.database_id}}
          digitalocean_token: ${{secrets.DO_TOKEN}}
